name: 'dbt_quant_finance'
version: '1.0.0'
config-version: 2

profile: 'dbt_quant_finance'

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_quant_finance:
    staging:
      +materialized: view
    marts:
      +materialized: table
