apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quant-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/your-repo.git
    targetRevision: main
    path: quant-finance-pipeline/gitops/base
  destination:
    server: https://kubernetes.default.svc
    namespace: quant-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
